### ISSUE TITLE
unf 0.2.0 does not install to a custom bundle path on linux

### ISSUE THREAD

**Issue by sfwester** [knu/ruby-unf#24]
# Overview

`unf` `0.2.0` requires rake to install on linux but, since it is only an install time dependency, is not codified into the gemspec.

This means that the install fails when installed by bundle into a non-default path where rake does not exists.

# Steps to reproduce

```sh
cat <<EOF > Dockerfile
FROM ruby:3.3.4-slim-bookworm

RUN mkdir -p /workdir/gems && \
    gem install bundler && \
    cd /workdir && \
    bundle init && \
    bundle config set --local path '/workdir/gems' && \
    bundle add unf --version '=0.2.0' && \
    bundle install
EOF
    
docker build -f Dockerfile .
```

# Actual Results

```
3.622 Fetching unf 0.2.0
3.761 Installing unf 0.2.0 with native extensions
3.929 Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
3.929 
3.929     current directory: /workdir/gems/ruby/3.3.0/gems/unf-0.2.0/ext
3.929 /usr/local/bin/ruby mkrf_conf.rb
3.929 
3.929 current directory: /workdir/gems/ruby/3.3.0/gems/unf-0.2.0/ext
3.929 rake
3.929 RUBYARCHDIR\=/workdir/gems/ruby/3.3.0/extensions/x86_64-linux/3.3.0/unf-0.2.0
3.929 RUBYLIBDIR\=/workdir/gems/ruby/3.3.0/extensions/x86_64-linux/3.3.0/unf-0.2.0
3.929 /usr/local/lib/ruby/3.3.0/rubygems.rb:259:in `find_spec_for_exe': can't find gem
3.929 rake (>= 0.a) with executable rake (Gem::GemNotFoundException)
3.929   from /usr/local/lib/ruby/3.3.0/rubygems.rb:278:in `activate_bin_path'
3.929   from /usr/local/bin/rake:25:in `<main>'
3.929 
3.929 rake failed, exit code 1
3.929 
3.929 Gem files will remain installed in /workdir/gems/ruby/3.3.0/gems/unf-0.2.0 for
3.929 inspection.
3.929 Results logged to
3.929 /workdir/gems/ruby/3.3.0/extensions/x86_64-linux/3.3.0/unf-0.2.0/gem_make.out
3.929 
3.929   /usr/local/lib/ruby/3.3.0/rubygems/ext/builder.rb:125:in `run'
3.929   /usr/local/lib/ruby/3.3.0/rubygems/ext/rake_builder.rb:30:in `build'
3.929   /usr/local/lib/ruby/3.3.0/rubygems/ext/builder.rb:193:in `build_extension'
3.929 /usr/local/lib/ruby/3.3.0/rubygems/ext/builder.rb:227:in `block in
3.929 build_extensions'
3.929   /usr/local/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `each'
3.929   /usr/local/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `build_extensions'
3.929   /usr/local/lib/ruby/3.3.0/rubygems/installer.rb:852:in `build_extensions'
3.929 /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/rubygems_gem_installer.rb:109:in
3.929 `build_extensions'
3.929 /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/rubygems_gem_installer.rb:28:in
3.929 `install'
3.929 /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/source/rubygems.rb:205:in
3.929 `install'
3.929 /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/installer/gem_installer.rb:54:in
3.929 `install'
3.929 /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/installer/gem_installer.rb:16:in
3.929 `install_from_spec'
3.929 /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/installer/parallel_installer.rb:132:in
3.929 `do_install'
3.929 /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/installer/parallel_installer.rb:123:in
3.929 `block in worker_pool'
3.929   /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/worker.rb:62:in `apply_func'
3.929 /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/worker.rb:57:in `block in
3.929 process_queue'
3.929   <internal:kernel>:187:in `loop'
3.929 /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/worker.rb:54:in
3.929 `process_queue'
3.929 /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/worker.rb:90:in `block (2
3.929 levels) in create_threads'
3.929 
3.929 An error occurred while installing unf (0.2.0), and Bundler cannot continue.
3.929 
3.929 In Gemfile:
3.929   unf
```

# Expected

The gem should install. (note the above does work if you remove the bundle config call)

It is not clear if it is appropriate for rake be added to the unf gemspec or something else should be different.

I spent some time to see if bundle could be configured to not lose access to the default gems but I came up empty.

**Comment by dorentus** [comment]
Same problem here.

Found a workaround: add `bundle add rake` just before `bundle add unf` and everything will be OK:

```sh
cat <<EOF > Dockerfile
FROM ruby:3.3.4-slim-bookworm

RUN mkdir -p /workdir/gems && \
    gem install bundler && \
    cd /workdir && \
    bundle init && \
    bundle config set --local path '/workdir/gems' && \
    bundle add rake && \
    bundle add unf --version '=0.2.0' && \
    bundle install
EOF
    
docker build -f Dockerfile .
```

Don't know why though.
